### ISSUE TITLE
Podcasts served by omny.fm errors out

### ISSUE THREAD

**Issue by xrogaan** [dvehrs/podget#70] opened 2023-05-30 21:25 UTC
I am trying to follow Dropped Frames (for reference https://omny.fm/shows/droppedframes). `podget` doesn't seem able to download anything from that server. Errors out with:

```
2023-05-30 23:15:08 URL:https://www.omnycontent.com/d/playlist/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/31f23a60-ba51-46ce-98b6-af380151517b/podcast.rss [306438/306438] -> "-" [1]

Downloading audio_source_Podcast_in_playlist_31f23a60-ba51-46ce-98b6-af380151517b.mp3 from https://traffic.omny.fm/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec
Read error (The request is invalid.) in headers.
Read error (The request is invalid.) in headers.
20 redirections exceeded.
```

Then marks all files as already downloaded.

A manual wget does works though.

**Comment by xrogaan** [comment] 2023-05-31 15:26
I didn't do a good job at filling this bug report, sorry. I am using podget 0.9, from debian testing. I should have tried with the most recent version afterward. I've done so just now and the issue still happens. However using the `--force` flag does trigger a proper download, I'm unsure if  `--force` is desirable through normal usage of the software though.

omnyFM does redirect you to a properly named file, but podget doesn't seem to take that name into account.

The line in my serverlist is:
```
https://omny.fm/shows/droppedframes/playlists/podcast.rss GAMES DroppedFrames OPT_FILENAME_RENAME_TITLETAG
```

Partial output with verbosity set to 4:
```
ORIGINAL FILENAME:             audio.mp3?utm_source=Podcast&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b
MODIFIED FILENAME:             audio_source=Podcast&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b.mp3
ORIGINAL TITLE:                Dropped Frames Episode 351
MODIFIED TITLE:                Dropped_Frames_Episode_351
Downloading audio_source=Podcast&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b.mp3 from https://traffic.omny.fm/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec
--2023-05-31 17:18:07--  https://traffic.omny.fm/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio.mp3?utm_source=Podcast&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b
Resolving traffic.omny.fm (traffic.omny.fm)... 2606:4700:10::6814:6b3e, 2606:4700:10::6814:6a3e, 104.20.106.62, ...
Connecting to traffic.omny.fm (traffic.omny.fm)|2606:4700:10::6814:6b3e|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://omny-east.mc.tritondigital.com/OMNY_DROPPEDFRAMES_PODCAST_P/media/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast [following]
--2023-05-31 17:18:07--  https://omny-east.mc.tritondigital.com/OMNY_DROPPEDFRAMES_PODCAST_P/media/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast
Resolving omny-east.mc.tritondigital.com (omny-east.mc.tritondigital.com)... 192.173.30.68
Connecting to omny-east.mc.tritondigital.com (omny-east.mc.tritondigital.com)|192.173.30.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 176073074 (168M) [audio/mpeg]
--2023-05-31 17:18:07--  https://omny-east.mc.tritondigital.com/OMNY_DROPPEDFRAMES_PODCAST_P/media/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast
Reusing existing connection to omny-east.mc.tritondigital.com:443.
HTTP request sent, awaiting response... 302 Temporarily Moved
Location: https://26133.mc.tritondigital.com:443/OMNY_DROPPEDFRAMES_PODCAST_P/media-session/77a302b2-ee7e-4055-acaf-aa7bbe119963/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast [following]
--2023-05-31 17:18:08--  https://26133.mc.tritondigital.com/OMNY_DROPPEDFRAMES_PODCAST_P/media-session/77a302b2-ee7e-4055-acaf-aa7bbe119963/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast
Resolving 26133.mc.tritondigital.com (26133.mc.tritondigital.com)... 208.92.55.44
Connecting to 26133.mc.tritondigital.com (26133.mc.tritondigital.com)|208.92.55.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 176073074 (168M) [audio/mpeg]
--2023-05-31 17:18:08--  https://26133.mc.tritondigital.com/OMNY_DROPPEDFRAMES_PODCAST_P/media-session/77a302b2-ee7e-4055-acaf-aa7bbe119963/d/clips/2a719a76-7cdb-4059-a7a0-af33012f7563/94ffb699-c5c9-4525-bf39-af3801515155/dbee3690-fcac-4dd6-9e43-b010013f05ec/audio/direct/t1685310320/Dropped_Frames_Episode_351.mp3?t=1685310320&in_playlist=31f23a60-ba51-46ce-98b6-af380151517b&utm_source=Podcast
Connecting to 26133.mc.tritondigital.com (26133.mc.tritondigital.com)|208.92.55.44|:443... connected.
HTTP request sent, awaiting response... 302 Temporarily Moved
```

**Comment by dvehrs** [comment] 2023-05-31 20:58
OK looking at the "full output" it appears there are a couple issues.

Let's start with a side issue the use of the --force option.  Basically all --force is doing is ignoring the logs of what has been downloaded before.   This is generally only useful for testing.  There are very rare occasions that a user will need to use it.  Mostly if they accidentally deleted a file and want to download a new copy.  This is not without pain as it will download every file in the feed again and so should be used with care and then with the --recent flag to only go as far back on the feed as necessary.  

Now let's get onto the issues.

**ISSUE 1:  The Items being "Marking as already downloaded..."**

This can only happen if you use the "--recent #" option on the command line or if you have configured MOST_RECENT in your podgetrc configuration file.  The default for MOST_RECENT is 0 and will download every file it finds in a feed.  When I add a new feed I commonly use "--recent 5" to just get the newest items from that feed. 

In your case since you are not using the --recent option on the command line, I suspect that you have configured MOST_RECENT=2 in your podgetrc.    You can change that to 0 and it will fix the problem for any new feeds you configure.  

For this feed, if you want it to be able to download all the items you will either need to use the --force option or to remove all the OMNY URLs from the done file in the Podget LOG directory.    As a general rule, in this case I would use a combination of --force and --recent to get the files I wanted. 

**ISSUE 2: 20 redirections exceeded**

It is interesting that you say that wget works when Podget does not because effectively Podget is a just a script wrapper around wget.  Podget uses wget to download the feed then parses the feed to get the enclosure URLs from it and then sequentially downloads each item with wget.   

Now the question is why are you getting so many redirects on the first couple items and what can we do about it.

The first part I confess I do not know why you are getting so many redirects but I suspect it has something to do with load balancing on the server.

So we are left with what can we do about it.

I believe the answer to this is also in your podgetrc file, although it is an option to wget that I have not included in the examples because I did not anticipate that it would ever need to be used.   What we need to do is to pass an additional configuration option to wget when it is called by the script.  

The option we need to pass to wget is "--max-redirects=number".

By default wget limits redirects to 20 which is why we are seeing the downloads halt when it hits that many redirects.

So to make this work, we may need to set it to a higher number.   How high?  I don't know.  On my testing here, when I use full verbosity I see that I'm getting three or four redirects but never 20.  I would probably start with 30 and go up from there.

So in your podgetrc, the option would look like:
```
WGET_BASEOPTS="-c -nH --max-redirects=30"
```

Now if you want to do that depends on how much you really want those couple files that Podget is having trouble getting.  Given that I'm not seeing the same problems here, I see no reason to believe that if you run Podget on another day that it won't eventually get those files.  When it had trouble with them, it should have added their URL to the errors log and will retry it in the next session as long as the feed is still configured in your serverlist.  

Good Luck,
Dave

**Comment by xrogaan** [comment] 2023-05-31 22:39
### Issue One

Yes, `MOST_RECENT` is set to 2. I don't intent to archive the whole thing, just listen to the last episodes. It's not an issue, podget does what is requested of it. However what we see as `Marking as already downloaded...` seems buggy. It's 20 lines about the same episode. I don't understand why the software would repeat it 20 times, or even mark something it failed to download as downloaded. That is an error.

I end up with 0 bytes length files.

### Issue Two

> It is interesting that you say that wget works when Podget does not because effectively Podget is a just a script wrapper around wget. 

I am aware, and I find it as strange as you do. Your suspicion about load balancing might be spot on. If that is the case, then the resolution ought not to with the amount of redirect done, but for how long we are trying. wget blast through the requests and is done under a minute. If the server wants to make the client wait, that length of time might need to be longer.

Trying to detect if podget actually manage to receive data and, if unsuccessful try again at a later time, would be an acceptable workaround. Could make use of the [atd daemon](https://packages.debian.org/bookworm/at):

```sh
# create a dedicated temporary serverlist containing failed feeds
echo 'podget --serverlist /tmp/podget.fail.session' | at now + 5 minute
```

Well, I don't know how you'd do it. I just find the atd daemon quite neat.

> I see no reason to believe that if you run Podget on another day that it won't eventually get those files.

You'd be correct. The wait time isn't counted in days, most likely in minutes. Might be failing because podget is too quick to download the audio file after hitting the rss feed? Can't really rely on common sense nowadays.

Anyhow, all this after I did an apt upgrade and rebooted. Then I ran 2 wget plus a podget command and they all started to download the audio file, though very slowly for the last one.

### Conclusion
Trying again at a later time is a simple workaround, if only podget could not mark the failed files as downloaded. Should I rename this issue to properly reflect that problem?

**Comment by dvehrs** [comment] 2023-06-01 16:55
**Issue One**

Two sub-issues but let's start with the important one.

First sub-issue:
>  I end up with 0 bytes length files.

Is that two files 0 byte length files or more?  If it is only for the two that MOST_RECENT allows for download then the issue is with how wget is configured.  I include the "-c" option to wget by default, this is configuration to continue downloading a partially downloaded file.  For that to work, whatever wget was able to download the first time is kept for the followup attempts.  In your case it resulted in 0 byte files because it never made it through the redirects.

I included the ability to continue downloads back when I first released Podget in 2005 because a large portion of the users were on dial-up connections and experiencing an interrupted download was more common. 

In this case we may have a bug but I'm not sure it is where you think it is.  If you look at line 3196 to 3206 of the 0.9.1 version of Podget, you will see a section that is called if a wget session exits with an error.  If that happens two things happen.  First the URL is added to the errors log and second if the file is a true zero length file it is removed.  So one of two things may be happening here.  Either wget is not exiting with an error condition or the file is just a hair bigger than a true zero file.  

Unfortunately so far I am unable to test either possibility because it always seems to work for me here.  I get a few redirects but never hit the 20 max.  I may be able to force redirects to something like 2 and see if that triggers anything.  I will let you know.

Second sub-issue:
>  However what we see as Marking as already downloaded... seems buggy. It's 20 lines about the same episode.

This is only what it appears to the user.    If you look in the done long, you will see each URL as it specified in the feed file.  What you will notice is that the FILENAME portion of each complete URL is the same.  The difference in the URL happens one level higher (so one slash before audio.mp3).  This is not the first feed that I've seen that does this.  There are a variety of old tricks that can be used in the podgetrc to account for it.  Unfortunately it may require you to use multiple podgetrc and serverlist files to account for the different possible combinations.

We know Podget is not buggy because of what we learned in the done log and because when we do not limit how many items Podget should download from the feed that it gets them all.  We also see the difference in when the filename changes in the URL to something human readable.  

The issue here is caused by trying to make Podget work with a variety of feeds and load balancing methods.  For what the user sees, Podget assumes the filename portion of the URL is correct.  As we can see from this feed and others, that is not always true and can be confusing to the user.  Now in this case if we used the TITLE that would be less confusing but then we might have issues with feeds that do not use TITLES.  So maybe we trigger that change if the TITLE change is enabled and found.   

Also this is a bit of a non-issue because if you run Podget multiple times with the --recent option enabled you will see that it marks the additional files as already download only on the first run.  After that the URLs are already in the log and so there is no need to mark them.  

**Issue Two**

The atd solution could work for people who  tend to use Podget exclusively manually from the command line.  However Podget was written to be run as a cron job.  So if you have enabled your Podget session in your users crontab file then it will rerun however often you have configured it to.   Podget does have a check built in that it checks for a current running session with the same configuration file if it is found then the new session exits.   The check for session file can be seen between lines 2050 and 2080 of Podget.   Given that ability, it is possible to have Podget run every minute, every hour, every day, or whatever period you want.  I know some people that wanted Podget to run very frequently to check for new episodes of their favorite podcasts but I personally run mine once a day so that I what I generally think of.

**Comment by dvehrs** [comment] 2023-06-01 17:03
OK, I may have found a bug.  When using the --recent option, there may be an issue with logging that results in the URLs that were considered recent to appear in both the done and errors log.   I was able to trigger that by setting --max-redirect=1.   This creates the wget error so they are logged to error log but then when I add the other URLs to the log I do not filter it for what was attempted.

Not sure why the files are not being deleted, they are zero size and pass the tests I use in the script so they should be.

So maybe two bugs.

**Comment by xrogaan** [comment] 2023-06-01 20:20
I don't particularly understand how podget function, it's a massive bash script in which I get lost. I would definitively not have used bash for this specific purpose :-P . I can't really help in pin-pointing why it doesn't work, I can only note that files aren't being downloaded and then considered as done.

I would personally use podget on a weekly basis. I doubt there are daily podcasts out there, and even if there are it's just too much content. So I would setup a weekly cronjob, or at minimum a job running every 3 days. Though, I don't see why the at command couldn't be run from the cron task. Too many unknowns I guess. However it would be used to try a download "at a later time", something that wget can help with as it is now. We could induce some wait time between requests wget is doing using the `-w` flag. It may help, at least with this one host, to induce a latency of one or two seconds between requests `wget -w 1.5 <url>`. This means that every time wget is answered with a 302, we wait a second before trying again. That behavior is entirely configurable on my end.

**Comment by dvehrs** [comment] 2023-06-01 20:49
Podget v0.1 was 302 lines long.   Podget 0.9.1 with the recent changes is 3778 lines long.   When it started it worked for the podcasts I tested it on but people asked for new features or bug fixes so it grew.  

It also got bigger as I tried to reduce dependencies.  That includes comments so I can figure out what I was thinking when I put a statement together.  This is very true for a couple of the sed expressions I use.  

And there are some old pieces commented out but still included so it can help me remember why we made some of the changes or in case we ever need to go back.

Probably half the script is DEBUG output or various statements for the user.  Helps when they know at least where the script fails.    

If I had it to do over would I do it in Bash?  I don't  know.  Some parts would be easier in other languages but I've got few complaints about how portable it is.  When I release a new version, I test it on Debian Linux, FreeBSD, NetBSD and OpenBSD.  There have also been users who have tested it on Windows Subsystem for Linux and on MacOS.   So it can be used almost everywhere and that is nice.  

FYI Just uploaded a new change to the DEV branch that enables the use of TITLES if configured for the "Marking as already downloaded...".  This should make it a bit clearer that it isn't just one URL repeating over and over.

And now onto the double logging in the done and errors log.

**Comment by dvehrs** [comment] 2023-06-02 20:23
OK I think I have a solution for the duplicate logging.  So far it is working but only tested on Debian.  I am curious if the sed statements I've built will require a little tweaking to be friendly on the BSDs.  Given that has happened before I wouldn't be surprised if it pops up again.  

I've uploaded these fixes into the DEV branch if you care to take a look.  They may be there a little while the full testing for a new version release takes more time than it should.

**Comment by xrogaan** [comment] 2023-06-04 22:43
So, this issue is very frustrating to me. I downloaded the recent podget with the changes you have made, added the waiting flag of 2 seconds, but I still get the `302 Temporarily Moved` loop. During one of those, I copied the url, opened another terminal and did a manual `wget <url>` request which went through right away. Done so twice.

For some reason, the string after `media-session` given by omnyfm keeps changing. Anyhow, I hit the same url, with the same IP. Yet doing so through podget somehow doesn't work most of the time. It might become simpler for me to create a small bash script to rip the podcast from youtube, given how we live in a service and DRM age.

**Comment by dvehrs** [comment] 2023-06-05 20:30
OK, two points. 

First I'm not sure the -w (wait) option for wget will have any effect because it adds an interval between downloads in wget.  That interval can only happen if one session of wget is downloading multiple files.  Podget downloads each file / URL as a single session of wget.  So as far as wget is concerned there is no place to put the wait time.

Also, there should already be an effective second or two between when the feed is downloaded and when the first file is downloaded because Podget needs time to parse the feed and check if the URL has already been downloaded or not.  The longer the feed file and the longer the log file then the longer the delay until it starts downloading.  

Second, the only way I can simulate this problem here is to set --max-redirect=1.  So I would wonder if that isn't a better option to play with that the wait (-w) option.  By default wget allows for 20 redirects.  What happens if you increase that to 30 or 40?

I'm really confused by the fact that with the same feed URL you and I are getting very different results.  We might need to look at your full configuration to see what other than MOST_RECENT you have changed that may or may not be having an effect.  

If that doesn't work then we may need to compare versions of various packages installed on your systems vs the versions installed  on mine to see if there is a difference there, but it's probably best to just start with the podget configuration options.

Is there anything nonstandard you are doing when you run podget?  Running it through TOR?  

Dave

**Comment by dvehrs** [comment] 2023-06-05 22:30
OK, was talking to a friend and he suggested testing podget in a clean shell environment to see if something you have configured it causing the issue.  Now I've done a little testing here and these two commands appear to work.  Basically all we need to do for the clean environment is make sure that $HOME is set.   So I run these two commands.

```
$ exec /usr/bin/env  -i bash --norc --noprofile
```

Then it starts a new session of bash which we can see is different by the prompt and we run Podget with the HOME variable configured.  

```
bash-5.2$ HOME=/home/<USERNAME> podget -vvvv 
```

Where USERNAME is your accounts username and assumes that you use standard locations for home directories.  

Might be worth a test to see if it works this way.  That could at least narrow down what the potential causes of the issue are.

Dave

**Comment by xrogaan** [comment] 2023-06-08 00:52
Couple of technical details first:

* the wait option makes wget wait between HTTP requests. So if the remote respond with a `302`, wget will need to create a new request towards the next location.
* I've tried with a clean shell, as described, without noticeable change.
* There will always be at least one redirect, as the surface url is apparently not the CDN. Most likely for analytics purpose. onmyfm is redirecting to triton digital. They aren't the same company, but both provides analytics.

I do believe it's an issue with the remote server not accepting my request. I'm located in Europe, so it may be affecting things. I would need to explore the response headers and figure out if there's something funky going on, but that's just too much hassle for me at the moment.

wget info, just in case:
```
~$ wget --version
GNU Wget 1.21.3 built on linux-gnu.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
+ntlm +opie +psl +ssl/gnutls 

Wgetrc: 
    /home/xrogaan/.wgetrc (user)
    /etc/wgetrc (system)
Locale: 
    /usr/share/locale 
Compile: 
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
    -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib 
    -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 
    -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -ffile-prefix-map=/build/wget-z9r8qt/wget-1.21.3=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
Link: 
    gcc -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -ffile-prefix-map=/build/wget-z9r8qt/wget-1.21.3=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall -Wl,-z,relro -Wl,-z,now 
    -lpcre2-8 -luuid -lidn2 -lnettle -lgnutls -lz -lpsl ../lib/libgnu.a 
```

.wgetrc
```
content-disposition = on
```

/etc/wgetrc
```
passive_ftp = on
```

**Comment by dvehrs** [comment] 2023-06-15 15:04
OK, finally got to do some testing with an older setup.  I tested on a Raspberry Pi that I have running Raspbian Bullseye.  

It has:
  Podget Version 0.9.0
  Wget Version 1.21

So only a little bit off of what I am using on Debian Sid for testing and development  (Podget version 0.9.1+ and Wget version 1.21.3).

It worked but I did see more redirects before wget was able to download the file.  On Debian Sid I pretty much averaged 1 redirect.   On the Raspbian system, I was seeing a minimum of 3 redirects and a high of 5.   

After that I adjusted my wgetrcs to match yours.  My /etc/wgetrc was already the same but I had to add .wgetrc.  No change.  

After that I attempted to use the OPT_CONTENT_DISPOSITION flag for Podget.  While this disables to view of progress meters, it did not create any other beneficial effects. 

After that I attempted to use the OPT_FILENAME_LOCATION flag for Podget.  It also disabled the progress meters but did not create any other beneficial effects.

So it appears that testing with an older version of wget might get a few more redirects but that is the only effect I see from Colorado.   I'm curious what can be causing the issue for a connection from Europe.  

More testing to come.

Dave

**Comment by dvehrs** [comment] 2024-01-02 20:42
OK, these patches were part of the new version 0.9.3 that was just released.   Lately the omny.fm is responding with fewer redirects that it used to.  So it is possible that they've fixed it on their end too.  Closing this for now.  If it becomes a problem again in the future just open a new issue and we'll dive in again.
Dave

**Closed by dvehrs** 2024-01-02 20:42 UTC
