### ISSUE TITLE
Filenames from Acast feed

### ISSUE THREAD

**Issue by benpollinger** [dvehrs/podget#35] opened 2017-09-13 21:50 UTC
Hello, I'm trying to work out options in podget to use a filename that does seem to be in the HTTP response. Unfortunately content-disposition header isn't given. 

However in the response below, it includes "filename=Griefcast-Ep-2-Jayde-Adams.mp3" but I can't work out how to get podget to rename media.mp3 to Griefcast-Ep-2-Jayde-Adams.mp3

```
wget --server-response https://media.acast.com/griefcast/episode-2-jayde-adams/media.mp3


HTTP request sent, awaiting response...
  HTTP/1.1 302 Found
  Cache-Control: no-cache, no-store, must-revalidate
  Content-Length: 381
  Content-Type: text/plain; charset=utf-8
  Location: https://mediacdn.acast.com/encoded/6b139f7b-0974-4b07-99fa-945390989       fd8/bb5fcc97-f748-4689-aab7-c043881fb30d/encoded-9e53cb27d36371069ab6cb34c6fbb6d5-128.mp3?ci=fa3b18b1-844a-432d-ab8a-039386d8eb23&aid=bb5fcc97-f748-4689-aab7-c0       43881fb30d&chid=6b139f7b-0974-4b07-99fa-945390989fd8&st=mmefRJZzpFkPGqofVIVOCQ&e
  =1505353271&filename=Griefcast-Ep-2-Jayde-Adams.mp3
  Vary: Accept
  Server: Microsoft-IIS/8.0
  Set-Cookie: TiPMix=90.0373209687124; path=/; Domain=media.acast.com
  Set-Cookie: media-RO=840746eba98133a3ca874168745af0c6; Path=/
  X-Powered-By: Express
  Arr-Disable-Session-Affinity: true
  Date: Wed, 13 Sep 2017 21:26:08 GMT
Location: https://mediacdn.acast.com/encoded/6b139f7b-0974-4b07-99fa-945390989fd       8/bb5fcc97-f748-4689-aab7-c043881fb30d/encoded-9e53cb27d36371069ab6cb34c6fbb6d5-       128.mp3?ci=fa3b18b1-844a-432d-ab8a-039386d8eb23&aid=bb5fcc97-f748-4689-aab7-c043       881fb30d&chid=6b139f7b-0974-4b07-99fa-945390989fd8&st=mmefRJZzpFkPGqofVIVOCQ&e=1
505353271&filename=Griefcast-Ep-2-Jayde-Adams.mp3 [following]
--2017-09-13 14:20:35--  https://mediacdn.acast.com/encoded/6b139f7b-0974-4b07-9       9fa-945390989fd8/bb5fcc97-f748-4689-aab7-c043881fb30d/encoded-9e53cb27d36371069a       b6cb34c6fbb6d5-128.mp3?ci=fa3b18b1-844a-432d-ab8a-039386d8eb23&aid=bb5fcc97-f748       -4689-aab7-c043881fb30d&chid=6b139f7b-0974-4b07-99fa-945390989fd8&st=mmefRJZzpFk
       PGqofVIVOCQ&e=1505353271&filename=Griefcast-Ep-2-Jayde-Adams.mp3
Resolving mediacdn.acast.com (mediacdn.acast.com)... 54.230.9.179, 54.230.9.127,
        54.230.9.253, ...
Connecting to mediacdn.acast.com (mediacdn.acast.com)|54.230.9.179|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Content-Type: audio/mpeg
  Content-Length: 46733817
  Connection: keep-alive
  Date: Sat, 26 Aug 2017 15:32:23 GMT
  Last-Modified: Wed, 10 May 2017 21:39:44 GMT
  ETag: "47cef99991a58fd90e96c08d15cf9b4c-9"
  x-amz-version-id: 0EeOEdvCmBHzsFtdFQnNzYEJzWfuDR1F
  Accept-Ranges: bytes
  Server: AmazonS3
  Age: 60707
  X-Cache: Hit from cloudfront
  Via: 1.1 fda8e723e76885a5a82b1728275c99fb.cloudfront.net (CloudFront)
  X-Amz-Cf-Id: cdOPnb8gbmSH5mOsZEzkrra2TCeBhIj4Xmm7bEstZ26uyKBKTGSuIg==
Length: 46733817 (45M) [audio/mpeg]
media.mp3: Permission denied
```

**Comment by dvehrs** [comment] 2017-09-14 00:47
The problem is you are mixing two options and expecting them to work the same.  If they worked the same, I would need only one flag to enable them.

The OPT_FILENAME_LOCATION looks for the "Location:" tag in the server response and returns everything before the question mark.  So it's discarding the part with the filename you want to use.

The OPT_CONTENT_DISPOSITION looks for the "Content Disposition" tag in the server response and extracts the filename from the "filename=" string.   Unfortunately we do not appear to have a "Content Disposition" tag to work with for this feed.

Yours is the first report of a LOCATION tag working the way the CONTENT DISPOSITION tag does.  Now can we add a way for PODGET to extract the name.  Maybe but it will probably require a third option to trigger the filtering and other small additions.

For a quick solution, I performed the download with FILENAME_FORMATFIX4 enabled and disabled both OPT_CONTENT_DISPOSITION and OPT_FILENAME_LOCATION.  Then rather than everything having the filename "media.mp3", they had names like "ep.10jackrooke_media.mp3" or "episode-1---adam-buxton_media.mp3".  The variation in filenames appears to depend on how verbose a name that they gave the directory holding the media.mp3 file.  As show by the enclosure URLs for the two files:

```
<enclosure url="https://media.acast.com/griefcast/ep.10jackrooke/media.mp3" length="45842031" type="audio/mpeg"/>
<enclosure url="https://media.acast.com/griefcast/episode-1---adam-buxton/media.mp3" length="104796204" type="audio/mpeg"/>
```

What do you think?

**Comment by benpollinger** [comment] 2017-09-14 20:52
Thanks again. I hadn't delved into the config file options so hadn't appreciated that there are so many workarounds in effect.

I think this feed used to give content-disposition but stopped working after about episode 7. I'm moving everything over from my old RaspPi to a new install on an odroidc2, so I'll test each feed in turn as I move them and see if it happens on other Acast feeds.

**Comment by benpollinger** [comment] 2017-09-14 21:10
Yes looks like something changed with Acast feeds at some point but I didn't pick it up because of the GnuTLS problem I wrote about in my other thread.

Looking at my old serverlist file and podgetrc, the default options used to give sensible filenames, e.g.
https://rss.acast.com/griefcast GENERAL Adam Buxton
gave me
adambuxton-ep34-adam-joe.mp3
... but after that something changed (though I can't be sure when the GnuTLS problem arose)

**Comment by dvehrs** [comment] 2017-09-30 15:10
Does this issue continue or has it been fixed by other system updates?

**Comment by dvehrs** [comment] 2019-05-23 23:07
Testing shows the FILENAME_FORMATFIX4 is working and I cannot confirm any other issues so I'm closing this issue.

If you have any continued issues, let me know.

**Closed by dvehrs** 2019-05-23 23:07 UTC
