### ISSUE TITLE
Problem with specifc 

### ISSUE THREAD

**Issue by vexillia** [dvehrs/podget#75] opened 2024-07-09 14:24 UTC
I have  a problem with this feed:  https://feeds.alitu.com/96872962.  It used to work but it no longer downloads anything but the first three episodes.

It doesn't validate either : https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.alitu.com%2F96872962

I suspect a malformed feed but can you shed any light on the ’cause?

Thanks.

**Comment by dvehrs** [comment] 2024-07-09 20:03
OK, it may be working here so I suspect there was a malformed feed that might have been corrected.

It still fails the validation test but when I try to download it I get 9 items instead of 3.  It appears to be one a week going back to May 7.    And it appears that the reasons the feed fails validation are not fields that Podget is concerned with so they are effectively ignored.  

I also tested with the OPT__FILENAME_RENAME_TITLETAG and the OPT_FILENAME_RENAME_MDATE options.  Both appeared to work the way they should for the nine items.  

One item that was mildly concerning was when I first downloaded the feed and used vim to look at it that it appeared to only have three lines.   The first line was 2718 characters long, the second line was 303 characters long and the third line was 10388 characters long.  So whatever they are using to generate the feed does not appear to be using any extra line breaks for formatting.   Now this doesn't appear to be affecting Podget because I did a quick count of the number of times there was an enclosure in the file and that was 9 times.  So it matched the number of files I was able to download.  

I also tested with Podget version 0.9.3 and with the latest version I am using for development.  Both produced the same results so I don't think there are any recent changes that caused or fixed any issues.  

Can you test it again and see if you get any different results?  

Dave

**Comment by vexillia** [comment] 2024-07-09 21:25
Thanks.  

[1] I cleared all the entries from the "done" file and tried again.     I got 9 entries in done.  7 downloads: episodes 1-6 & 9 but the filename of 9 wasn't changed as 1-6 were.

[2] Tried again and got this in done:

https://feeds.alitu.com/96872962/19a24050-09db-4655-8c5d-5437b9c4e439.mp3?t=1715097981000
https://feeds.alitu.com/96872962/e4dc059d-0f97-417d-ac72-8176f44e998d.mp3?t=1715693282000
https://feeds.alitu.com/96872962/184fe829-ea4c-42fd-b846-8563078fda5a.mp3?t=1716839499000
https://feeds.alitu.com/96872962/c2487017-76c6-4c70-9f1a-fb3d5280d21e.mp3?t=1717538346000
https://feeds.alitu.com/96872962/facc9cb0-4b70-4341-baa8-c025e86d99be.mp3?t=1718185137000
https://feeds.alitu.com/96872962/d975f2dd-fc11-4170-bda1-0cdb2df08a1a.mp3?t=1718812682000
https://feeds.alitu.com/96872962/6b81ab4a-38fb-412b-9614-0e2dfca60826.mp3?t=1719320889000
https://feeds.alitu.com/96872962/c6c23d17-7809-4d98-8f83-b98e777444b8.mp3?t=1720036985000
https://feeds.alitu.com/96872962/c06e905e-8458-4589-8a9f-a1c22ad0b62c.mp3?t=1720531530000

So 9 episodes but now only the first 6 downloaded.  This was the key part of the output from podget:

Marking as already downloaded 6b81ab4a-38fb-412b-9614-0e2dfca60826.mp3?t=1719320889000.
Marking as already downloaded c6c23d17-7809-4d98-8f83-b98e777444b8.mp3?t=1720036985000.
Marking as already downloaded c06e905e-8458-4589-8a9f-a1c22ad0b62c.mp3?t=1720531530000.

Full output for the podcast attached:

[20240709 - podget output.txt](https://github.com/user-attachments/files/16150685/20240709.-.podget.output.txt)

This is from podgetrc:

# Most Recent
# 0  == download all new items.
# 1+ == download only the <count> most recent
MOST_RECENT=6

# Force
# 0 == Only download new material.
# 1 == Force download all items even those you've downloaded before.
FORCE=0

I'm confused: it's picking the first 6 not the last 6.

Also found this in errors file:

https://podcasts.apple.com/us/podcast/james-matt-on-sport/id1745142813?uo=4

**Comment by vexillia** [comment] 2024-07-09 21:40
PS here's the feed file:

[20240709 - rssviewer.txt](https://github.com/user-attachments/files/16150867/20240709.-.rssviewer.txt)

Maybe you can see some malformed code.  (I can't :-()

**Comment by vexillia** [comment] 2024-07-09 21:49
There's  more:

If I run podget -r 1it picks up episode 6 as the latest file.

**Comment by vexillia** [comment] 2024-07-09 21:53
If I run podget -r 1 it picks up episode 1 not 9!  Not what I expected.

**Comment by dvehrs** [comment] 2024-07-10 02:50
OK, it appears you have two issues happening.   One appears to be because of the format of the feed and one may be because the documentation is not entirely clear.

Let's first look at the first issue which is caused by the format of the feed.  As a general rule, feeds can either add new items to the top of the list (descending order) or to the bottom (ascending order).  In my experience, most feeds do the first so that the newest stuff is at the top.   However some feeds like to add new to the bottom because it makes sense to them.  This feed appears to be of the second type.    This is why when you restrict it to download only a single item (-r 1) that it only grabs the first item in the list and it happens to be the oldest episode.  

By default Podget assumes that the feed will list from newest to oldest items.   In this case, we need to change that.  To do so, add the OPT_FEED_ORDER_ASCENDING to the line in your serverlist file.    Then when Podget downloads the list with '-r 1', it will only download episode 9 and not 1.

Next, why it only downloaded 6 of the 9 episodes.  

The "Marking as already downloaded ..." message is for when there are items in the list but you have hit your limit set with -r, --recent or set with MOST_RECENT in your podgetrc.   It marks them by simply adding their URL to the LOG_COMPLETE file so that the next time Podget is run it will not try to download them again.   

As a general rule, in my podgetrc I keep MOST_RECENT=0 so that all items are downloaded.  Then if I want to limit an individual feed when I first download it I use the -r or --recent command  line options to set how many to get before marking them as already downloaded.   Then it goes back to downloading any new URLs in the feed that are not already in the LOG_COMPLETE file.  In this case, for a feed with nine items I wouldn't use a recent limit.   It just wouldn't save enough time to be worth it.   Most times I use recent is for feeds that have dozens of items and have not cleared their history anytime.  


Now one other small issue.   Not really an issue but we can make things a bit easier for you.  As you discovered you can get podget to download items another time by removing their URL from the LOG_COMPLETE file.  However we can skip past that by either enabling FORCE=1 in our podgetrc or using the '--force' option on the command line.  When we do that Podget does not check the LOG_COMPLETE file to see if an item has already been downloaded, if it has it deletes it then downloads a fresh copy.    So in a situation like this where I am testing a feed.  Rather than manually removing entries from the LOG_COMPLETE file I will just use the '--force' combined with '--recent [1-9]' to determine how many items I want to get.  

One other issue when you are working with a single feed it can be a hassle if you have a bunch of other feeds in your serverlist.  I get around that by creating a new serverlist file for just the new feed.   Then either using the CONFIG_SERVERLIST option in the podgetrc or the '--serverlist filename' option on the command line to specify it.  Then when I'm happy that the feed is in a state ready for regular use, I copy its line to my core everyday feed list that is automatically called from crontab.    

Hopefully that clears some things up without adding too much new information to muddy the waters.  
Dave

**Comment by vexillia** [comment] 2024-07-10 08:06
Thanks.  Using OPT_FEED_ORDER_ASCENDING solved the problem.  It all makes sense now.

Finally, thanks for the tips on using a specific server list when testing new feeds.

I really appreciate the help with this.

**Closed** 2024-07-10 08:07 UTC
